# Generated by Django 2.1.4 on 2019-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.DecimalField(decimal_places=2.0, max_digits=9),
        ),
    ]
