# Generated by Django 2.1.5 on 2019-02-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestscore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bestscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='user',
        ),
        migrations.AddField(
            model_name='boughtgame',
            name='game_state',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='boughtgame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BestScore',
        ),
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
