# Generated by Django 2.1.4 on 2019-01-15 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
