# Generated by Django 2.1.4 on 2019-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('type',)},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='labels',
            new_name='label',
        ),
    ]
