# Generated by Django 2.1.4 on 2019-02-08 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtgame',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boughtgame',
            name='bought_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
