# Generated by Django 2.1.4 on 2019-01-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190118_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='label',
        ),
        migrations.AddField(
            model_name='game',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Label'),
        ),
    ]
