# Generated by Django 2.1.4 on 2019-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
